"""roles & areas & user FKs (+audio.area_id opcional)

Revision ID: 9e0d96ef535e
Revises: b9cdd334d7d3
Create Date: 2025-10-23 12:57:24.885965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0d96ef535e'
down_revision: Union[str, Sequence[str], None] = 'b9cdd334d7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audios_area_id'), 'audios', ['area_id'], unique=False)
    op.create_foreign_key(None, 'audios', 'areas', ['area_id'], ['id'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_area_id'), 'users', ['area_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'users', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_area_id'), table_name='users')
    op.drop_column('users', 'area_id')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'audios', type_='foreignkey')
    op.drop_index(op.f('ix_audios_area_id'), table_name='audios')
    op.drop_column('audios', 'area_id')
    # ### end Alembic commands ###
